# Generated by Django 3.1.4 on 2021-03-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_auto_20210303_0714'),
        ('siteview', '0002_brandintroduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='Product')),
            ],
        ),
    ]
