# Generated by Django 3.1.4 on 2021-01-01 08:44

import Accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20201231_1014'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Accounts.models.UserManger()),
            ],
        ),
    ]
