# Generated by Django 3.1.4 on 2021-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210101_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='satisfaction',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='satisfaction'),
        ),
    ]
