# Generated by Django 3.1.4 on 2021-02-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20210212_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='satisfaction',
            field=models.PositiveIntegerField(blank=True, default=3, null=True, verbose_name='satisfaction'),
        ),
    ]
