# Generated by Django 3.1.4 on 2021-02-20 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210212_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', related_query_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
