# Generated by Django 3.1.4 on 2021-02-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_applyingforshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyingforshop',
            options={'verbose_name': 'shop request', 'verbose_name_plural': 'shop requests'},
        ),
    ]
