# Generated by Django 3.1.4 on 2021-03-03 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_auto_20210302_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', related_query_name='user_shop', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
