# Generated by Django 3.1.4 on 2020-12-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20201231_1034'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_item', related_query_name='basket_item', to='Order.basket', verbose_name='Basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.shopproduct', verbose_name='Shop product'),
        ),
    ]
