# Generated by Django 3.1.4 on 2021-02-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20210209_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
