# Generated by Django 3.1.4 on 2021-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20201231_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/category/image'),
        ),
    ]
