# Generated by Django 3.1.4 on 2021-02-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_shop_satisfaction'),
        ('Products', '0006_auto_20210205_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'Shop Products', 'verbose_name_plural': 'Shop Products'},
        ),
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together={('product', 'shop')},
        ),
    ]
