# Generated by Django 3.1.4 on 2021-02-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20210211_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
