# Generated by Django 3.1.4 on 2021-03-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_auto_20210303_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_meta', related_query_name='product_meta', to='Products.product', verbose_name='product'),
        ),
    ]
